name: build

on:
  push:
    branches:
      - 'main'
    tags:
      - 'testbuild*'
  pull_request:

permissions:
    contents: write
    packages: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: 1.20.0
          cache: true
      - run: go install fyne.io/fyne/v2/cmd/fyne@latest
      - run: fyne package --release
      - uses: actions/upload-artifact@v4
        with:
          name: rye-fyne
          path: rye-fyne.exe
